// <auto-generated />
using System;
using DbLayer.Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DbLayer.Migrations
{
    [DbContext(typeof(DbEntity))]
    [Migration("20200206050637_initials1")]
    partial class initials1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DbLayer.Framework.Tables.SA_LicenseInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Application_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_lock")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_used")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAC_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SA_LicenseInformation");
                });

            modelBuilder.Entity("DbLayer.Framework.Tables.SA_Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SA_Login");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 2, 6, 10, 36, 37, 501, DateTimeKind.Local).AddTicks(6864),
                            Is_deleted = false,
                            Password = "admin",
                            UpdatedAt = new DateTime(2020, 2, 6, 10, 36, 37, 502, DateTimeKind.Local).AddTicks(5525),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("DbLayer.Framework.Tables.User_Information", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_lock")
                        .HasColumnType("bit");

                    b.Property<bool>("Is_used")
                        .HasColumnType("bit");

                    b.Property<int>("License_id")
                        .HasColumnType("int");

                    b.Property<string>("Mobile_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("License_id");

                    b.ToTable("user_Information");
                });

            modelBuilder.Entity("DbLayer.Framework.Tables.User_Information", b =>
                {
                    b.HasOne("DbLayer.Framework.Tables.SA_LicenseInformation", "SA_LicenseInformation")
                        .WithMany("user_Information")
                        .HasForeignKey("License_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
